export const apiCatalog = [
  {
    id: "universal-search",
    family: "search",
    mode: "offline",
    path: "/api/v3/echotik/search/items",
    method: "GET",
    summary: "Search across creators, products, sellers, videos, and live sessions",
    docsUrl: "https://opendocs.echotik.live/echotik/search/items.md",
    keywords: ["search", "find", "find creators", "find products", "find shops", "find videos", "keyword"],
    requiredParams: ["sk", "type", "size"],
    recommendedParams: ["region", "searchType", "sortType"],
    sourceNote: "Fallback search endpoint only. Returns at most 30 results and lighter fields than detail or list endpoints."
  },
  {
    id: "influencer-list",
    family: "influencer",
    mode: "offline",
    path: "/api/v3/echotik/influencer/list",
    method: "GET",
    summary: "Bulk-filter the offline creator database for discovery and research",
    docsUrl: "https://opendocs.echotik.live/echotik/influencer/list.md",
    keywords: ["creator", "influencer", "kol", "commerce creator", "creator list"],
    requiredParams: [],
    recommendedParams: ["region", "product_category_id", "influencer_sort_field_v2", "sort_type", "page_num", "page_size"],
    sourceNote: "Offline EchoTik dataset. Suitable for advanced multi-condition filtering and typically T+1.",
    emptyFallbackId: "realtime-influencer-detail"
  },
  {
    id: "influencer-ranklist",
    family: "influencer",
    mode: "offline",
    path: "/api/v3/echotik/influencer/ranklist",
    method: "GET",
    summary: "Retrieve creator leaderboards for Top-N, growth-ranking, and periodic ranking use cases",
    docsUrl: "https://opendocs.echotik.live/echotik/influencer/ranklist.md",
    keywords: ["creator leaderboard", "follower growth ranking", "ranking", "top creators", "fastest-growing creators"],
    requiredParams: [],
    recommendedParams: ["region", "date", "rank_type", "page_num", "page_size", "sort_type"],
    sourceNote: "Periodic EchoTik leaderboard, T+1. Weekly and monthly leaderboards require correctly back-shifted period dates."
  },
  {
    id: "influencer-trend",
    family: "influencer",
    mode: "offline",
    path: "/api/v3/echotik/influencer/trend",
    method: "GET",
    summary: "Retrieve creator trend snapshots for historical growth and interaction analysis",
    docsUrl: "https://opendocs.echotik.live/echotik/influencer/trend.md",
    keywords: ["creator trend", "follower growth trend", "historical trend"],
    requiredParams: ["user_id"],
    recommendedParams: ["start_date", "end_date"],
    sourceNote: "Supports up to 180 days. Non-contiguous dates usually indicate unchanged metrics on missing days."
  },
  {
    id: "influencer-detail",
    family: "influencer",
    mode: "offline",
    path: "/api/v3/echotik/influencer/detail",
    method: "GET",
    summary: "Batch-retrieve creator detail records",
    docsUrl: "https://opendocs.echotik.live/echotik/influencer/detail.md",
    keywords: ["creator detail", "creator profile", "influencer profile"],
    requiredParams: ["user_ids_or_unique_ids"],
    recommendedParams: [],
    sourceNote: "Supports comma-separated batch input. This belongs to a dual-mode creator-detail workflow with the realtime variant.",
    dualModeGroup: "creator-detail"
  },
  {
    id: "realtime-influencer-detail",
    family: "influencer",
    mode: "realtime",
    path: "/api/v3/realtime/influencer/detail",
    method: "GET",
    summary: "Retrieve creator detail in realtime",
    docsUrl: "https://opendocs.echotik.live/realtime/influencer/detail.md",
    keywords: ["realtime creator", "latest creator detail", "live creator profile"],
    requiredParams: ["unique_id"],
    recommendedParams: [],
    sourceNote: "Use this when the latest creator profile state is required.",
    dualModeGroup: "creator-detail"
  },
  {
    id: "influencer-category-name",
    family: "influencer",
    mode: "offline",
    path: "/api/v3/echotik/influencer/category_name",
    method: "GET",
    summary: "Retrieve the creator category enumeration set",
    docsUrl: "https://opendocs.echotik.live/echotik/influencer/category_name.md",
    keywords: ["creator categories", "creator category enum", "influencer categories"],
    requiredParams: [],
    recommendedParams: [],
    sourceNote: "Use only when creator list or creator rank list requires category filtering."
  },
  {
    id: "influencer-video-list",
    family: "influencer",
    mode: "offline",
    path: "/api/v3/echotik/influencer/video/list",
    method: "GET",
    summary: "Retrieve a creator's offline video list",
    docsUrl: "https://opendocs.echotik.live/echotik/influencer/video/list.md",
    keywords: ["creator videos", "creator video list", "influencer videos"],
    requiredParams: ["user_id_or_unique_id"],
    recommendedParams: ["page_num", "page_size", "product_id"],
    sourceNote: "The offline variant returns enhanced fields such as sales, GMV, and trend-related metrics.",
    dualModeGroup: "creator-video-list"
  },
  {
    id: "realtime-influencer-video-list",
    family: "influencer",
    mode: "realtime",
    path: "/api/v3/realtime/influencer/video/list",
    method: "GET",
    summary: "Retrieve a creator's video list in realtime",
    docsUrl: "https://opendocs.echotik.live/realtime/influencer/video/list.md",
    keywords: ["realtime creator videos", "latest creator videos", "live creator video list"],
    requiredParams: ["unique_id"],
    recommendedParams: ["offset"],
    sourceNote: "The realtime variant is better for the latest content, but does not include offline sales and GMV enhancement fields.",
    dualModeGroup: "creator-video-list",
    paginationModel: "max_cursor",
    idResolution: "If only user_id is available, resolve unique_id through influencer-detail first."
  },
  {
    id: "realtime-influencer-follower-list",
    family: "influencer",
    mode: "realtime",
    path: "/api/v3/realtime/influencer/follower/list",
    method: "GET",
    summary: "Retrieve a creator's follower list in realtime",
    docsUrl: "https://opendocs.echotik.live/realtime/influencer/follower/list.md",
    keywords: ["creator followers", "follower list", "audience list"],
    requiredParams: ["user_id"],
    recommendedParams: ["offset"],
    sourceNote: "Use min_time as the next offset for pagination.",
    paginationModel: "min_time"
  },
  {
    id: "realtime-influencer-following-list",
    family: "influencer",
    mode: "realtime",
    path: "/api/v3/realtime/influencer/following/list",
    method: "GET",
    summary: "Retrieve a creator's following list in realtime",
    docsUrl: "https://opendocs.echotik.live/realtime/influencer/following/list.md",
    keywords: ["creator following", "following list", "accounts followed"],
    requiredParams: ["user_id"],
    recommendedParams: ["offset"],
    sourceNote: "Use min_time as the next offset for pagination.",
    paginationModel: "min_time"
  },
  {
    id: "realtime-influencer-region",
    family: "influencer",
    mode: "realtime",
    path: "/api/v3/realtime/influencer/region",
    method: "GET",
    summary: "Retrieve a creator's region in realtime",
    docsUrl: "https://opendocs.echotik.live/realtime/influencer/region.md",
    keywords: ["creator region", "creator country", "creator location"],
    requiredParams: ["unique_id"],
    recommendedParams: [],
    sourceNote: "If this endpoint fails, attempt realtime-influencer-video-list and infer region from the first returned video.",
    idResolution: "If only user_id is available, resolve unique_id through influencer-detail first."
  },
  {
    id: "realtime-influencer-generate-qrcode",
    family: "influencer",
    mode: "realtime",
    path: "/api/v3/realtime/influencer/generate/qrcode",
    method: "GET",
    summary: "Generate a creator homepage QR code",
    docsUrl: "https://opendocs.echotik.live/realtime/influencer/generate/qrcode.md",
    keywords: ["creator qr code", "creator homepage qr", "profile qr code"],
    requiredParams: ["user_id"],
    recommendedParams: [],
    sourceNote: "Use this when the user explicitly needs a homepage QR code for a creator."
  },
  {
    id: "realtime-influencer-milestones",
    family: "influencer",
    mode: "realtime",
    path: "/api/v3/realtime/influencer/milestones_insight",
    method: "GET",
    summary: "Retrieve creator milestone data in realtime",
    docsUrl: "https://opendocs.echotik.live/realtime/influencer/milestones_insight.md",
    keywords: ["creator milestones", "milestone insight", "follower milestones", "creator achievements"],
    requiredParams: ["user_id"],
    recommendedParams: [],
    sourceNote: "Returns milestone events such as follower and view thresholds reached over time."
  },
  {
    id: "influencer-live-list",
    family: "influencer",
    mode: "offline",
    path: "/api/v3/echotik/influencer/live/list",
    method: "GET",
    summary: "Retrieve a creator's historical live-session list",
    docsUrl: "https://opendocs.echotik.live/echotik/influencer/live/list.md",
    keywords: ["creator live sessions", "influencer live history", "historical live streams"],
    requiredParams: ["user_id"],
    recommendedParams: ["page_num", "page_size"],
    sourceNote: "Best suited for research into a creator's historical live-stream activity."
  },
  {
    id: "influencer-product-list",
    family: "influencer",
    mode: "offline",
    path: "/api/v3/echotik/influencer/product/list",
    method: "GET",
    summary: "Retrieve the products historically promoted by a creator",
    docsUrl: "https://opendocs.echotik.live/echotik/influencer/product/list.md",
    keywords: ["creator promoted products", "creator storefront", "what a creator sold"],
    requiredParams: ["user_id"],
    recommendedParams: ["page_num", "page_size", "product_category_id"],
    sourceNote: "Primarily returns the relationship between creators and products."
  },
  {
    id: "product-category-l1",
    family: "product",
    mode: "offline",
    path: "/api/v3/echotik/category/l1",
    method: "GET",
    summary: "Retrieve the product L1 category list",
    docsUrl: "https://opendocs.echotik.live/echotik/category/l1.md",
    keywords: ["product categories", "l1 category", "top-level category"],
    requiredParams: ["language"],
    recommendedParams: [],
    sourceNote: "Use this first when the user supplies only a broad product category."
  },
  {
    id: "product-category-l2",
    family: "product",
    mode: "offline",
    path: "/api/v3/echotik/category/l2",
    method: "GET",
    summary: "Retrieve the product L2 category list",
    docsUrl: "https://opendocs.echotik.live/echotik/category/l2.md",
    keywords: ["product subcategories", "l2 category", "second-level category"],
    requiredParams: ["parent_id", "language"],
    recommendedParams: [],
    sourceNote: "Resolve L2 only after the correct L1 parent category is known."
  },
  {
    id: "product-category-l3",
    family: "product",
    mode: "offline",
    path: "/api/v3/echotik/category/l3",
    method: "GET",
    summary: "Retrieve the product L3 category list",
    docsUrl: "https://opendocs.echotik.live/echotik/category/l3.md",
    keywords: ["product leaf categories", "l3 category", "third-level category"],
    requiredParams: ["parent_id", "language"],
    recommendedParams: [],
    sourceNote: "Resolve L3 only after the correct L2 parent category is known."
  },
  {
    id: "seller-category-l1",
    family: "seller",
    mode: "offline",
    path: "/api/v3/echotik/seller/category/l1",
    method: "GET",
    summary: "Retrieve the seller-category L1 list",
    docsUrl: "https://opendocs.echotik.live/echotik/seller/category/l1.md",
    keywords: ["seller categories", "shop categories", "seller l1 category"],
    requiredParams: ["language"],
    recommendedParams: [],
    sourceNote: "Use this first when the user supplies only a broad seller or shop category."
  },
  {
    id: "seller-category-l2",
    family: "seller",
    mode: "offline",
    path: "/api/v3/echotik/seller/category/l2",
    method: "GET",
    summary: "Retrieve the seller-category L2 list",
    docsUrl: "https://opendocs.echotik.live/echotik/seller/category/l2.md",
    keywords: ["seller subcategories", "shop subcategories", "seller l2 category"],
    requiredParams: ["parent_id", "language"],
    recommendedParams: [],
    sourceNote: "Resolve L2 only after the correct seller-category L1 parent is known."
  },
  {
    id: "seller-category-l3",
    family: "seller",
    mode: "offline",
    path: "/api/v3/echotik/seller/category/l3",
    method: "GET",
    summary: "Retrieve the seller-category L3 list",
    docsUrl: "https://opendocs.echotik.live/echotik/seller/category/l3.md",
    keywords: ["seller leaf categories", "shop leaf categories", "seller l3 category"],
    requiredParams: ["parent_id", "language"],
    recommendedParams: [],
    sourceNote: "Resolve L3 only after the correct seller-category L2 parent is known."
  },
  {
    id: "product-list",
    family: "product",
    mode: "offline",
    path: "/api/v3/echotik/product/list",
    method: "GET",
    summary: "Bulk-filter the offline product database for breakout-product research",
    docsUrl: "https://opendocs.echotik.live/echotik/product/list.md",
    keywords: ["product", "winning product", "product sourcing", "product list"],
    requiredParams: [],
    recommendedParams: ["region", "category_id", "off_mark", "sort", "page_num", "page_size"],
    sourceNote: "Offline EchoTik dataset. Unless the user explicitly requests off-shelf products, pass off_mark=0 for in-market products."
  },
  {
    id: "product-trend",
    family: "product",
    mode: "offline",
    path: "/api/v3/echotik/product/trend",
    method: "GET",
    summary: "Retrieve product trend snapshots for historical sales and GMV analysis",
    docsUrl: "https://opendocs.echotik.live/echotik/product/trend.md",
    keywords: ["product trend", "product growth trend", "historical product trend"],
    requiredParams: ["product_id"],
    recommendedParams: ["start_date", "end_date"],
    sourceNote: "Supports up to 180 days. Missing dates usually indicate unchanged tracked metrics on those days."
  },
  {
    id: "product-detail",
    family: "product",
    mode: "offline",
    path: "/api/v3/echotik/product/detail",
    method: "GET",
    summary: "Batch-retrieve product detail records",
    docsUrl: "https://opendocs.echotik.live/echotik/product/detail.md",
    keywords: ["product detail", "product profile"],
    requiredParams: ["product_ids"],
    recommendedParams: [],
    sourceNote: "Supports up to 10 comma-separated product IDs. If offline detail is empty, ask whether to switch to the realtime detail endpoint, which requires region.",
    dualModeGroup: "product-detail"
  },
  {
    id: "realtime-product-detail",
    family: "product",
    mode: "realtime",
    path: "/api/v3/realtime/product/detail_new_app",
    method: "GET",
    summary: "Retrieve product detail in realtime",
    docsUrl: "https://open.echotik.live/api/v3/realtime/product/detail_new_app",
    keywords: ["realtime product detail", "latest product detail", "live product profile"],
    requiredParams: ["product_id", "region"],
    recommendedParams: [],
    sourceNote: "Realtime product-detail path supplied by the project rules. Requires an explicit region.",
    dualModeGroup: "product-detail"
  },
  {
    id: "realtime-product-photo-search",
    family: "search",
    mode: "realtime",
    path: "/api/v3/realtime/product/photo-search",
    method: "POST",
    summary: "Search products from a base64 image",
    docsUrl: "https://opendocs.echotik.live/realtime/product/photo-search.md",
    keywords: ["image product search", "photo product search", "search product by image"],
    requiredParams: ["image_base64"],
    recommendedParams: [],
    sourceNote: "Use raw base64 without a data URL prefix. Pair with the photo-search page endpoint for more results."
  },
  {
    id: "realtime-product-photo-search-page",
    family: "search",
    mode: "realtime",
    path: "/api/v3/realtime/product/photo-search/page",
    method: "POST",
    summary: "Paginate additional product results after a photo search",
    docsUrl: "https://opendocs.echotik.live/realtime/product/photo-search/page.md",
    keywords: ["photo search pagination", "more image search products"],
    requiredParams: ["image_uri", "box_detection"],
    recommendedParams: [],
    sourceNote: "Use the image_uri and box_detection returned by the initial photo-search request."
  },
  {
    id: "realtime-product-search",
    family: "product",
    mode: "realtime",
    path: "/api/v3/realtime/product/search",
    method: "GET",
    summary: "Search products in realtime",
    docsUrl: "https://opendocs.echotik.live/realtime/product/search.md",
    keywords: ["realtime product search", "latest products", "live product search"],
    requiredParams: ["keyword"],
    recommendedParams: ["offset", "region"]
  },
  {
    id: "realtime-influencer-search",
    family: "search",
    mode: "realtime",
    path: "/api/v3/realtime/influencer/search",
    method: "GET",
    summary: "Search creators in realtime",
    docsUrl: "https://opendocs.echotik.live/realtime/influencer/search.md",
    keywords: ["search creators", "creator search", "influencer search"],
    requiredParams: ["keyword"],
    recommendedParams: ["offset", "region"]
  },
  {
    id: "extract-product-id",
    family: "product",
    mode: "realtime",
    path: "/api/v3/realtime/extract_product_id",
    method: "GET",
    summary: "Extract a product ID from a product share link",
    docsUrl: "https://opendocs.echotik.live/realtime/extract_product_id.md",
    keywords: ["product link", "extract product id", "share link"],
    requiredParams: ["url"],
    recommendedParams: [],
    sourceNote: "Use this first whenever the user provides a product share link instead of a canonical product_id."
  },
  {
    id: "product-comment",
    family: "product",
    mode: "offline",
    path: "/api/v3/echotik/product/comment",
    method: "GET",
    summary: "Retrieve collected offline product comments",
    docsUrl: "https://opendocs.echotik.live/echotik/product/comment.md",
    keywords: ["product comments", "product reviews", "offline product comments"],
    requiredParams: ["product_id"],
    recommendedParams: ["page_num", "page_size"],
    sourceNote: "Offline collected comments may lag behind the latest public comments.",
    dualModeGroup: "product-comments"
  },
  {
    id: "realtime-product-comment",
    family: "product",
    mode: "realtime",
    path: "/api/v3/realtime/product/comment",
    method: "GET",
    summary: "Retrieve product comments in realtime",
    docsUrl: "https://opendocs.echotik.live/realtime/product/comment.md",
    keywords: ["realtime product comments", "latest product comments", "product reviews realtime"],
    requiredParams: ["product_id", "region"],
    recommendedParams: ["offset"],
    sourceNote: "Start from offset=1. If has_more=true, use next_cursor as the next offset.",
    dualModeGroup: "product-comments",
    paginationModel: "next_cursor"
  },
  {
    id: "product-influencer-list",
    family: "product",
    mode: "offline",
    path: "/api/v3/echotik/product/influencer/list",
    method: "GET",
    summary: "Retrieve creators associated with a product",
    docsUrl: "https://opendocs.echotik.live/echotik/product/influencer/list.md",
    keywords: ["product creators", "who promoted this product"],
    requiredParams: ["product_id"],
    recommendedParams: ["page_num", "page_size"],
    sourceNote: "Returns creator relationships only. Use creator detail endpoints for deeper creator fields."
  },
  {
    id: "product-video-list",
    family: "product",
    mode: "offline",
    path: "/api/v3/echotik/product/video/list",
    method: "GET",
    summary: "Retrieve videos associated with a product",
    docsUrl: "https://opendocs.echotik.live/echotik/product/video/list.md",
    keywords: ["product videos", "commerce videos for a product"],
    requiredParams: ["product_id"],
    recommendedParams: ["page_num", "page_size", "user_id", "start_date", "end_date"],
    sourceNote: "Supports publish-time filtering, creator user_id filtering, and product_id filtering."
  },
  {
    id: "product-live-list",
    family: "product",
    mode: "offline",
    path: "/api/v3/echotik/product/live/list",
    method: "GET",
    summary: "Retrieve live sessions associated with a product",
    docsUrl: "https://opendocs.echotik.live/echotik/product/live/list.md",
    keywords: ["product live sessions", "product live list", "live commerce for a product"],
    requiredParams: ["product_id"],
    recommendedParams: ["page_num", "page_size"]
  },
  {
    id: "product-ranklist",
    family: "product",
    mode: "offline",
    path: "/api/v3/echotik/product/ranklist",
    method: "GET",
    summary: "Retrieve product leaderboards for sales and creator-promotion ranking",
    docsUrl: "https://opendocs.echotik.live/echotik/product/ranklist.md",
    keywords: ["product ranking", "top products", "best-selling products", "hot promoted products"],
    requiredParams: [],
    recommendedParams: ["region", "date", "rank_type", "page_num", "page_size"],
    sourceNote: "Periodic EchoTik leaderboard, T+1. Weekly and monthly leaderboards require correctly back-shifted period dates."
  },
  {
    id: "seller-list",
    family: "seller",
    mode: "offline",
    path: "/api/v3/echotik/seller/list",
    method: "GET",
    summary: "Bulk-filter the offline seller database",
    docsUrl: "https://opendocs.echotik.live/echotik/seller/list.md",
    keywords: ["shop", "seller", "shop list", "store"],
    requiredParams: [],
    recommendedParams: ["region", "category_id", "is_cross_border", "commerce_mode", "sort", "page_num", "page_size"],
    sourceNote: "Offline EchoTik dataset, T+1. Suitable for category-driven, cross-border/local, and commerce-mode seller filtering."
  },
  {
    id: "seller-trend",
    family: "seller",
    mode: "offline",
    path: "/api/v3/echotik/seller/trend",
    method: "GET",
    summary: "Retrieve seller trend snapshots for historical sales analysis",
    docsUrl: "https://opendocs.echotik.live/echotik/seller/trend.md",
    keywords: ["shop trend", "seller trend", "historical shop trend"],
    requiredParams: ["seller_id"],
    recommendedParams: ["start_date", "end_date"],
    sourceNote: "Supports up to 180 days. Missing dates usually indicate unchanged tracked metrics on those days."
  },
  {
    id: "seller-detail",
    family: "seller",
    mode: "offline",
    path: "/api/v3/echotik/seller/detail",
    method: "GET",
    summary: "Retrieve seller detail",
    docsUrl: "https://opendocs.echotik.live/echotik/seller/detail.md",
    keywords: ["shop detail", "seller detail", "store profile"],
    requiredParams: ["seller_id"],
    recommendedParams: [],
    sourceNote: "If code=0 and data is empty, the shop is not collected in EchoTik offline data."
  },
  {
    id: "seller-product-list",
    family: "seller",
    mode: "offline",
    path: "/api/v3/echotik/seller/product/list",
    method: "GET",
    summary: "Retrieve a seller's product list",
    docsUrl: "https://opendocs.echotik.live/echotik/seller/product/list.md",
    keywords: ["seller products", "shop products", "what the shop sells"],
    requiredParams: ["seller_id"],
    recommendedParams: ["page_num", "page_size"],
    sourceNote: "Offline inventory may differ from realtime inventory and can include historically listed products that are no longer on sale.",
    dualModeGroup: "seller-product-list"
  },
  {
    id: "realtime-seller-product-list",
    family: "seller",
    mode: "realtime",
    path: "/api/v3/realtime/seller/product/list",
    method: "GET",
    summary: "Retrieve a seller's product list in realtime",
    docsUrl: "https://opendocs.echotik.live/realtime/seller/product/list.md",
    keywords: ["realtime seller products", "latest shop products", "live seller inventory"],
    requiredParams: ["seller_id", "region"],
    recommendedParams: ["scroll_param"],
    sourceNote: "The first request may omit the pagination token. If has_more=true, use next_scroll_param for the next page.",
    dualModeGroup: "seller-product-list",
    paginationModel: "next_scroll_param"
  },
  {
    id: "seller-influencer-list",
    family: "seller",
    mode: "offline",
    path: "/api/v3/echotik/seller/influencer/list",
    method: "GET",
    summary: "Retrieve creators associated with a seller",
    docsUrl: "https://opendocs.echotik.live/echotik/seller/influencer/list.md",
    keywords: ["seller creators", "shop creators", "creator partners"],
    requiredParams: ["seller_id"],
    recommendedParams: ["page_num", "page_size"],
    sourceNote: "Returns seller-to-creator relationships only. Use creator detail endpoints for deeper creator fields."
  },
  {
    id: "seller-video-list",
    family: "seller",
    mode: "offline",
    path: "/api/v3/echotik/seller/video/list",
    method: "GET",
    summary: "Retrieve videos associated with a seller",
    docsUrl: "https://opendocs.echotik.live/echotik/seller/video/list.md",
    keywords: ["shop videos", "seller videos", "store commerce videos"],
    requiredParams: ["seller_id"],
    recommendedParams: ["page_num", "page_size"]
  },
  {
    id: "seller-live-list",
    family: "seller",
    mode: "offline",
    path: "/api/v3/echotik/seller/live/list",
    method: "GET",
    summary: "Retrieve live sessions associated with a seller",
    docsUrl: "https://opendocs.echotik.live/echotik/seller/live/list.md",
    keywords: ["shop live sessions", "seller live sessions", "store live streams"],
    requiredParams: ["seller_id"],
    recommendedParams: ["page_num", "page_size"]
  },
  {
    id: "seller-ranklist",
    family: "seller",
    mode: "offline",
    path: "/api/v3/echotik/seller/ranklist",
    method: "GET",
    summary: "Retrieve seller leaderboards for local versus cross-border and hot-sale versus hot-promotion ranking",
    docsUrl: "https://opendocs.echotik.live/echotik/seller/ranklist.md",
    keywords: ["shop ranking", "seller ranking", "top shops", "cross-border shops", "local shops"],
    requiredParams: [],
    recommendedParams: ["region", "date", "rank_type", "seller_type", "page_num", "page_size"],
    sourceNote: "Periodic EchoTik leaderboard. Use the same T+1 and date-alignment logic as the product leaderboard family."
  },
  {
    id: "video-list",
    family: "video",
    mode: "offline",
    path: "/api/v3/echotik/video/list",
    method: "GET",
    summary: "Bulk-filter the offline video database",
    docsUrl: "https://opendocs.echotik.live/echotik/video/list.md",
    keywords: ["video", "hot videos", "video list"],
    requiredParams: [],
    recommendedParams: ["region", "is_commerce_video", "is_ai_video", "is_ad_video", "product_category_id", "product_id", "page_num", "page_size"],
    sourceNote: "Supports large-scale discovery across commerce videos, AI videos, and ad videos with advanced filtering."
  },
  {
    id: "video-trend",
    family: "video",
    mode: "offline",
    path: "/api/v3/echotik/video/trend",
    method: "GET",
    summary: "Retrieve historical trend snapshots for a video",
    docsUrl: "https://opendocs.echotik.live/echotik/video/trend.md",
    keywords: ["video trend", "historical video trend", "video growth trend"],
    requiredParams: ["video_id"],
    recommendedParams: ["start_date", "end_date"],
    sourceNote: "Supports up to 180 days. Prefer realtime 14-day trend for short-horizon accuracy."
  },
  {
    id: "video-detail",
    family: "video",
    mode: "offline",
    path: "/api/v3/echotik/video/detail",
    method: "GET",
    summary: "Batch-retrieve video detail records",
    docsUrl: "https://opendocs.echotik.live/echotik/video/detail.md",
    keywords: ["video detail", "video metrics"],
    requiredParams: ["video_ids"],
    recommendedParams: [],
    sourceNote: "Supports up to 10 comma-separated video IDs and includes offline sales, GMV, and enriched recent interaction metrics.",
    dualModeGroup: "video-detail",
    emptyFallbackId: "realtime-video-detail"
  },
  {
    id: "video-ranklist",
    family: "video",
    mode: "offline",
    path: "/api/v3/echotik/video/ranklist",
    method: "GET",
    summary: "Retrieve leaderboard-style rankings for commerce and AI videos",
    docsUrl: "https://opendocs.echotik.live/echotik/video/ranklist.md",
    keywords: ["video ranking", "top videos", "ai videos", "top commerce videos"],
    requiredParams: [],
    recommendedParams: ["region", "product_category_id", "is_ai_video", "date", "rank_type", "page_num", "page_size"],
    sourceNote: "Periodic EchoTik leaderboard. Use the same T+1 and date-alignment logic as the other leaderboard families."
  },
  {
    id: "realtime-video-detail",
    family: "video",
    mode: "realtime",
    path: "/api/v3/realtime/video/detail",
    method: "GET",
    summary: "Retrieve video detail in realtime",
    docsUrl: "https://opendocs.echotik.live/realtime/video/detail.md",
    keywords: ["realtime video", "latest video detail"],
    requiredParams: ["video_id"],
    recommendedParams: [],
    dualModeGroup: "video-detail"
  },
  {
    id: "realtime-video-captions",
    family: "video",
    mode: "realtime",
    path: "/api/v3/realtime/video/captions",
    method: "GET",
    summary: "Retrieve captions or script text for a video in realtime",
    docsUrl: "https://opendocs.echotik.live/realtime/video/captions.md",
    keywords: ["video captions", "video script", "caption extraction"],
    requiredParams: ["video_id"],
    recommendedParams: [],
    sourceNote: "May return multi-language scripts."
  },
  {
    id: "realtime-video-comments",
    family: "video",
    mode: "realtime",
    path: "/api/v3/realtime/video/comments",
    method: "GET",
    summary: "Retrieve a video's comment list",
    docsUrl: "https://opendocs.echotik.live/realtime/video/comments.md",
    keywords: ["video comments", "comment list"],
    requiredParams: ["video_id"],
    recommendedParams: ["cursor", "count"]
  },
  {
    id: "realtime-video-search",
    family: "search",
    mode: "realtime",
    path: "/api/v3/realtime/video/search",
    method: "GET",
    summary: "Search videos in realtime",
    docsUrl: "https://opendocs.echotik.live/realtime/video/search.md",
    keywords: ["search videos", "video search", "find videos by keyword"],
    requiredParams: ["keyword"],
    recommendedParams: ["offset", "region"]
  },
  {
    id: "realtime-video-comment-replies",
    family: "video",
    mode: "realtime",
    path: "/api/v3/realtime/video/comments/replies",
    method: "GET",
    summary: "Retrieve replies for a specific video comment",
    docsUrl: "https://opendocs.echotik.live/realtime/video/comments/replies.md",
    keywords: ["comment replies", "video replies", "reply list"],
    requiredParams: ["video_id", "comment_id"],
    recommendedParams: ["cursor", "count"]
  },
  {
    id: "realtime-video-comment-insight",
    family: "video",
    mode: "realtime",
    path: "/api/v3/realtime/video/comment_keywords_insight",
    method: "GET",
    summary: "Retrieve keyword insight from the top comments of a video",
    docsUrl: "https://opendocs.echotik.live/realtime/video/comment_keywords_insight.md",
    keywords: ["comment keyword insight", "why it performed", "comment analysis"],
    requiredParams: ["video_id"],
    recommendedParams: []
  },
  {
    id: "realtime-video-trend-insight",
    family: "video",
    mode: "realtime",
    path: "/api/v3/realtime/video/trend_insight",
    method: "GET",
    summary: "Retrieve the 14-day interaction trend for a video",
    docsUrl: "https://opendocs.echotik.live/realtime/video/trend_insight.md",
    keywords: ["14-day trend", "interaction trend", "video trend"],
    requiredParams: ["video_id"],
    recommendedParams: []
  },
  {
    id: "video-product-list",
    family: "video",
    mode: "offline",
    path: "/api/v3/echotik/video/product/list",
    method: "GET",
    summary: "Retrieve products associated with a video",
    docsUrl: "https://opendocs.echotik.live/echotik/video/product/list.md",
    keywords: ["video products", "products attached to a video"],
    requiredParams: ["video_ids"],
    recommendedParams: []
  },
  {
    id: "realtime-video-downloadurl",
    family: "video",
    mode: "realtime",
    path: "/api/v3/realtime/video/downloadurl",
    method: "GET",
    summary: "Retrieve video download URLs from a share link",
    docsUrl: "https://opendocs.echotik.live/realtime/video/downloadurl.md",
    keywords: ["download video", "video download url", "shared video link"],
    requiredParams: ["url"],
    recommendedParams: []
  },
  {
    id: "realtime-hashtag-video-list",
    family: "video",
    mode: "realtime",
    path: "/api/v3/realtime/hashtag/video/list",
    method: "GET",
    summary: "Retrieve videos associated with a hashtag",
    docsUrl: "https://opendocs.echotik.live/realtime/hashtag/video/list.md",
    keywords: ["hashtag videos", "videos for hashtag", "hashtag related videos"],
    requiredParams: ["hashtag_id"],
    recommendedParams: ["cursor", "count"],
    sourceNote: "If only hashtag text is known, resolve hashtag_id through realtime hashtag search first."
  },
  {
    id: "realtime-live-detail",
    family: "live",
    mode: "realtime",
    path: "/api/v3/realtime/live/detail",
    method: "GET",
    summary: "Retrieve live-room detail",
    docsUrl: "https://opendocs.echotik.live/realtime/live/detail.md",
    keywords: ["live detail", "live room metrics"],
    requiredParams: ["room_id", "user_id"],
    recommendedParams: [],
    sourceNote: "This endpoint requires the livestream to be actively live. Ended rooms may return no data."
  },
  {
    id: "realtime-live-search",
    family: "live",
    mode: "realtime",
    path: "/api/v3/realtime/live/search",
    method: "GET",
    summary: "Search live sessions in realtime",
    docsUrl: "https://opendocs.echotik.live/realtime/live/search.md",
    keywords: ["search live", "live search"],
    requiredParams: ["keyword"],
    recommendedParams: ["offset", "region"]
  },
  {
    id: "realtime-hashtag-search",
    family: "trend",
    mode: "realtime",
    path: "/api/v3/realtime/hashtag/search",
    method: "GET",
    summary: "Search hashtags",
    docsUrl: "https://opendocs.echotik.live/realtime/hashtag/search.md",
    keywords: ["hashtag", "hashtag search", "topic search"],
    requiredParams: ["keyword"],
    recommendedParams: ["region", "offset"]
  },
  {
    id: "realtime-music-search",
    family: "trend",
    mode: "realtime",
    path: "/api/v3/realtime/music/search",
    method: "GET",
    summary: "Search music in realtime",
    docsUrl: "https://opendocs.echotik.live/realtime/music/search.md",
    keywords: ["music search", "bgm", "music"],
    requiredParams: ["keyword"],
    recommendedParams: ["offset", "region"]
  },
  {
    id: "batch-cover-download",
    family: "utility",
    mode: "offline",
    path: "/api/v3/echotik/batch/cover/download",
    method: "POST",
    summary: "Convert EchoTik cover URLs into temporary accessible image URLs",
    docsUrl: "https://opendocs.echotik.live/echotik/batch/cover/download.md",
    keywords: ["cover download", "temporary image url", "convert cover url"],
    requiredParams: ["cover_url"],
    recommendedParams: [],
    sourceNote: "Only works for URLs hosted on echosell-images.tos-ap-southeast-1.volces.com and does not consume usage credits."
  }
];

export const regionMap = {
  "united states": "US",
  "usa": "US",
  "us": "US",
  "美国": "US",
  "united kingdom": "GB",
  "uk": "GB",
  "great britain": "GB",
  "英国": "GB",
  "indonesia": "ID",
  "印尼": "ID",
  "thailand": "TH",
  "泰国": "TH",
  "vietnam": "VN",
  "越南": "VN",
  "philippines": "PH",
  "菲律宾": "PH",
  "malaysia": "MY",
  "马来西亚": "MY",
  "singapore": "SG",
  "新加坡": "SG",
  "brazil": "BR",
  "巴西": "BR",
  "mexico": "MX",
  "墨西哥": "MX"
};

export const typeMap = {
  influencer: 1,
  creator: 1,
  "达人": 1,
  "创作者": 1,
  product: 2,
  "商品": 2,
  seller: 3,
  shop: 3,
  "店铺": 3,
  "小店": 3,
  video: 4,
  "视频": 4,
  live: 5
};
